version: "3.7"
services:
    server:
        build: .
        environment:
#            - rs.comport=/dev/ttyACM0
            - rs.baud_rate=4800
#            - rs.data_bits=8
#            - rs.stop_bits=1
#            - rs.parity=none
#            - rs.flow_control=none
#            - rs.timeout=1
            - rs.message_delimiter=11,101
#        ports:
#            - "8080:8080"
#        volumes:
#            - .:/app