version: "3.7"
services:
    server:
        build: .
        restart: unless-stopped
        container_name: serial-ports-server
        environment:
            - rs.baud_rate=9600
            - rs.message_delimiter=11,101
#            - ws.endpoint=/echo
        ports:
            - "8080:8080"
        volumes:
            - .:/app/logs
        devices:
            - /dev/ttyS0:/dev/ttyS0
            - /dev/ttyS2:/dev/ttyS2
            - /dev/ttyS1:/dev/ttyS1
            - /dev/ttyACM0:/dev/ttyACM0
            - /dev:/dev
        privileged: true