version: "3.7"
services:
    server:
        build: .
        restart: unless-stopped
        container_name: serial-ports-server
        environment:
            - rs.baud_rate=9600
            - rs.message_delimiter=13,10  # 10 = \n, 13 = \r
            - ws.heartbeat.interval=2000  # value in ms > 1
#            - ws.endpoint=/echo
        ports:
            - "8080:8080"
        volumes:
            - /logs :/app/logs
        devices:
            - /dev/ttyS0:/dev/ttyS0
            - /dev/ttyS2:/dev/ttyS2
            - /dev/ttyS1:/dev/ttyS1
            - /dev/ttyACM0:/dev/ttyACM0
            - /dev:/dev
        privileged: true