version: "3.7"
services:
    server:
        build: .
        restart: unless-stopped
        container_name: serial-ports-server
        environment:
#            - rs.comport=/dev/ttyACM0
            - rs.baud_rate=9600
#            - rs.data_bits=8
#            - rs.stop_bits=1
#            - rs.parity=none
#            - rs.flow_control=none
#            - rs.timeout=1
            - rs.message_delimiter=11,101
        ports:
            - "8080:8080"
#        volumes:
#            - .:/app
        devices:
            - /dev/ttyS0:/dev/ttyS0
            - /dev/ttyS2:/dev/ttyS2
            - /dev/ttyS1:/dev/ttyS1
            - /dev/ttyACM0:/dev/ttyACM0
            - /dev:/dev
        privileged: true