services:
    server:
        build: .
        restart: unless-stopped
        container_name: serial-ports-server
        environment:
            - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m
            - rs.comports=COM1,S0
            - rs.baud_rate=9600
            - rs.message_delimiter=13,10  # 10 = \n, 13 = \r
            - ws.heartbeat.interval=2000  # value in ms > 1
            - ip.db-client=192.168.2.4:8085
        ports:
            - "443:443"
            - "8081:8081"
        networks:
          backend:
        healthcheck:
          test: ["CMD", "netcat", "-z", "localhost", "443"]
          interval: 5s
          timeout: 5s
          retries: 3
          start_period: 10s
        volumes:
            - ./logs:/app/logs
            - server-data:/app
        devices:
            - /dev/ttyS0:/dev/ttyS0
            - /dev/ttyS2:/dev/ttyS2
            - /dev/ttyS1:/dev/ttyS1
            - /dev/ttyACM0:/dev/ttyACM0
            - /dev:/dev
        privileged: true
        depends_on:
          mariadb:
            condition: service_healthy
    mariadb:
      image: mariadb:11.7@sha256:81e893032978c4bf8ad43710b7a979774ed90787fa32d199162148ce28fe3b76
      restart: unless-stopped
      container_name: mariadb
      environment:
        - MARIADB_USER=user
        - MARIADB_PASSWORD=password
        - MARIADB_DATABASE=certificates
        - MARIADB_ROOT_PASSWORD=root
      volumes:
        - mariadb-data:/var/lib/mysql
      expose:
        - "3306"
      ports:
        - "3306:3306"
      networks:
        - backend
      healthcheck:
        test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
        interval: 5s
        timeout: 5s
        retries: 3
        start_period: 10s

networks:
  backend:
    name: backend
    attachable: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"

volumes:
  mariadb-data:
    name: db-data
  server-data:
    name: server-data
